### ISSUE TITLE
Docs still link to etl/datastore

### ISSUE THREAD

**Issue by lb-** [openeemeter/eemeter#141]
Hi.

Just exploring the eemeter project and noticed that these links are incorrect or out of date:

https://eemeter.readthedocs.io/en/latest/etl_installation.html
* ETL project seems to no longer be on Github

https://eemeter.readthedocs.io/en/latest/datastore_index.html
* datastore project seems to no longer be on Github

**Comment by mdrpheus** [comment]
Was the datastore integrated into the project? I was doing some research and it seems like eemeter could use [iotdb](https://arxiv.org/abs/1605.01435) or [btrdb](https://www.usenix.org/system/files/conference/fast16/fast16-papers-andersen.pdf).

**Comment by mdrpheus** [comment]
Oh I found [this link to the datastore](https://eemeter.readthedocs.io/en/latest/datastore_index.html). It seems to have been using the Django ORM to a PostgreSQL database.

**Comment by philngo** [comment]
Thanks for the interest! We were concerned that the ETL library and datastore library were more complicated than was necessary, so we deprecated those at the eemeter 1.0.0 release (https://github.com/openeemeter/eemeter/releases/tag/v1.0.0). The documentation, as you noticed, still reflects that they are in use, which is a mistake. The documentation issue is on our radar and we will remove the references ASAP, as they are confusing and out of date. The current recommended usage of the eemeter library is through the CLI, described at https://www.openee.io/open-source/get-started. The API documentation for the eemeter (not datastore/etl which are gone) which is deployed on readthedocs is still relevant.

**Comment by philngo** [comment]
I'll make a note in this issue when it is resolved then close this issue at that time. Leaving it open for now as it is still unresolved.

**Comment by LogicLady** [comment]
Thanks for all the details! You can disregard the question I sent you earlier then, Phil. This answers it!

**Comment by philngo** [comment]
Resolved in eemeter 2.0.0
