### ISSUE TITLE
Best way to contribute?

### ISSUE THREAD

**Issue by mdrpheus** [openeemeter/eemeter#150]
Hello,

I was wondering what the best way to contribute to this project might be. Most of my experience is with front-end stuff with React/Angular (although I am by no means a master of it) and I was wondering if I could perhaps contribute towards a basic GUI/charting system for the project.

**Comment by philngo** [comment]
Hi mdrpheus, thank you for reaching out. We appreciate those willing to spend time to improve the eemeter. Although this may not be your specialty, we welcome contributions to the CLI, documentation, or formatting. We currently have some flake8 issues that need to be resolved as well. If you make a change, please make a fork and a pull request with descriptions of the change, how it can be tested and we will review it.

**Comment by mdrpheus** [comment]
Thanks @philngo!
