### ISSUE TITLE
pip install eemeter failing to install. Is statsmodels the culprit or just a symptom?

### ISSUE THREAD

**Issue by matthewgee** [openeemeter/eemeter#31]
An issue that Devan from Kilowatt Analytics ran into trying to `pip install eemeter`

![image](https://cloud.githubusercontent.com/assets/320542/23631849/648f2d3c-0285-11e7-88b2-f5c02e89e5c4.png)

> I’m guessing this issue is due to the eemeter install not completing without errors. Having just repeated the process I realize that ‘pip install eemeter’ is failing due to an issue with lxml. I had to manually apt-get install lxml as I was previously warned that it was not present when trying to install eemeter. Maybe there’s a lxml version dependency that is causing an issue. Regardless, I cannot seem to install eemeter following the instructions on either github or RTD

**Comment by matthewgee** [comment]
Success!
> I’ve managed to successfully install eemeter. It turned out I needed to install lbml and zlib to get the pip install eemeter to complete wihtout errors. Zlib was the last holdout, but I finally realized that’s where the compile was failing.

**Comment by matthewgee** [comment]
Two ideas for resolving this issue from @marcpare and @philngo:

- Create a docker or vagrant install option
- Recommend first installing anaconda/miniconda for new eemeter users

**Comment by philngo** [comment]
See #32 for proposed new installation instructions.
