### ISSUE TITLE
can't load sample data

### ISSUE THREAD

**Issue by kielni** [openeemeter/eemeter#330]
I'm trying load sample data as described in http://eemeter.openee.io/basics.html#loading-sample-data. I tried with both 1.5.1 (pip install) and 2.2.6 (pip install git+git://github.com/openeemeter/eemeter.git@v2.2.6), both with python 3.6.0

running `eemeter.samples()` with 1.5.1 fails with `module 'eemeter' has no attribute 'samples'`

```
(eemeter) ~/work/platform $ pip install eemeter
Installing collected packages: eemeter
Successfully installed eemeter-1.5.1
(eemeter) ~/work/platform $ python3
Python 3.6.0 (default, Sep 12 2017, 20:42:47)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
>>> import eemeter
>>> eemeter.samples()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'eemeter' has no attribute 'samples'
>>>
```

running `eemeter.samples()` with 2.2.6 fails with `FileNotFoundError: [Errno 2] No such file or directory: '/Users/kimberly/.pyenv/versions/eemeter/lib/python3.6/site-packages/eemeter/samples/metadata.json'`

```
(eemeter) ~/work/platform $ pip install git+git://github.com/openeemeter/eemeter.git@v2.2.6
Successfully installed eemeter-2.2.6
(eemeter) ~/work/platform $ python3
Python 3.6.0 (default, Sep 12 2017, 20:42:47)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
>>> import eemeter
>>> eemeter.samples()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kimberly/.pyenv/versions/eemeter/lib/python3.6/site-packages/eemeter/samples/load.py", line 45, in samples
    sample_metadata = _load_sample_metadata()
  File "/Users/kimberly/.pyenv/versions/eemeter/lib/python3.6/site-packages/eemeter/samples/load.py", line 32, in _load_sample_metadata
    with resource_stream("eemeter.samples", "metadata.json") as f:
  File "/Users/kimberly/.pyenv/versions/eemeter/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1208, in resource_stream
    self, resource_name
  File "/Users/kimberly/.pyenv/versions/eemeter/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1573, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kimberly/.pyenv/versions/eemeter/lib/python3.6/site-packages/eemeter/samples/metadata.json'
```

I expected it to load sample data as described on http://eemeter.openee.io/basics.html#loading-sample-data

I'm using MacOS High Sierra 10.13.6 and python 3.6.0

**Comment by philngo** [comment]
Thanks for the bug report. I've reproduced this locally and I think I found a quick fix. While we work on a better fix for this, you should be able to get around it for now by instead installing in "editable" mode:

```
pip install -e git+git://github.com/openeemeter/eemeter.git@v2.2.6#egg=eemeter
```

Will you let me know if that works for you? That worked for me after reproducing your error. If it does, I'll close this out and reference this better install command in the other issue where we explain how to install the 2.x.x series. The samples will only work in 2.x.x, not in 1.5.x.

**Comment by kielni** [comment]
Yes, that worked, thank you!
