### ISSUE TITLE
loading sample data

### ISSUE THREAD

**Issue by blipscomb9** [openeemeter/eemeter#338]
- Trying to follow the tutorial for loading sample data: https://eemeter.readthedocs.io/basics.html#loading-sample-data
- On: Windows 10, Python 3.6.8, EEMeter 2.3.0
- eemeter.samples correctly gives me the list of sample data available. When I try to load_sample per tutorial syntax I get the following error:

>>> meter_data, temperature_data, metadata = \
... eemeter.load_sample('il-electricity-cdd-hdd-daily')
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "c:\users\ben\src\eemeter\eemeter\samples\load.py", line 82, in load_sample
    meter_data = meter_data_from_csv(f, gzipped=True, freq=freq)
  File "c:\users\ben\src\eemeter\eemeter\io.py", line 83, in meter_data_from_csv
    df = pd.read_csv(filepath_or_buffer, **read_csv_kwargs).tz_localize("UTC")
  File "C:\Users\Ben\Anaconda3\envs\OpenEE\lib\site-packages\pandas\core\generic.py", line 9407, in tz_localize
    ax = _tz_localize(ax, tz, ambiguous, nonexistent)
  File "C:\Users\Ben\Anaconda3\envs\OpenEE\lib\site-packages\pandas\core\generic.py", line 9387, in _tz_localize
    'PeriodIndex' % ax_name)
TypeError: index is not a valid DatetimeIndex or PeriodIndex

**Comment by philngo** [comment]
Thanks for the report. We haven't yet made `eemeter` fully compatible with the latest pandas release, which introduced breaking changes to an API we were previously using. If you downgrade your pandas installation to  `pandas<=0.23.4`, the data loading should work.

**Comment by blipscomb9** [comment]
Thanks Phil, that did the trick.

**Comment by houghb** [comment]
Hi Phil, aside from loading sample data does pandas 0.24 cause any other known issues with running eemeter?

**Comment by philngo** [comment]
Yes - it causes errors generally with the way we're using time series indexes on meter and temperature data.
