### ISSUE TITLE
Parse and graph temperatures in degC

### ISSUE THREAD

**Issue by sb-oeh** [openeemeter/eemeter#347]
Can you please add functionality to receive temperature in degC (not just degF) and to plot graphs using degC, too?

(incl. .plot_time_series etc.)

**Comment by philngo** [comment]
Did you run into a specific error trying to use degC? You should be able to, including with .plot_time_series, although you may need to change the default ranges. The eemeter package is designed to be unit agnostic, with a couple of exceptions where default heating/cooling balance point search ranges are defined in degF, but these can be overridden. The sample data is given in degF, but you should be able to use everything with degC. If you do run into issues, please report them here.

**Comment by sb-oeh** [comment]
Thanks for getting back to me.
No I converted to degF first due to the default heating/cooling balance points. Yes, I've heard you can change the default ranges so I will look into that. Before I do, I also suspect using degC widens the balance point increment search (i.e. 3degC is wider than 3degF). Does this code search in units of 3 for the balance point?
See links below:
http://docs.caltrack.org/en/latest/technical-appendix.html#maximum-gap-between-candidate-balance-points-in-the-grid-search-is-3-degrees-f-or-the-equivalent-in-degrees-c
http://docs.caltrack.org/en/latest/methods.html#methods3-2-3

**Comment by philngo** [comment]
The balance points need not be integers, but the 3 °F limit is intended to apply to °C as well. (i.e., 3 Δ°F = 3 / 1.8 Δ°C ~= 1.667Δ°C). So any grid search with intervals less than or equal to that should be caltrack compliant. For example,  [-1.111 °C, -0.555 °C, 0 °C, 0.555 °C, 1.111 °C, ...  32.22222 °C] is the equivalent of the °F default of [30°F, 31°F, 32°F, ..., 90°F]. Hope that helps.
