### ISSUE TITLE
PyPI only has tarballs for version 1.5.1

### ISSUE THREAD

**Issue by yurivict** [openeemeter/eemeter#348]
https://pypi.org/project/eemeter/

**Comment by philngo** [comment]
Hi yurivict, we are working toward a resolution to that matter. Please see #318 for alternative installation instructions and and #344 for further discussion of the resolution.

**Comment by philngo** [comment]
@yurivict Just letting you know eemeter 2.x.x is now on PyPI.

**Comment by yurivict** [comment]
Thank you.
