### ISSUE TITLE
pip install installs eemeter-2.5.3.post2 instead of 2.5.4 

### ISSUE THREAD

**Issue by jefffriesen** [openeemeter/eemeter#351]
Loading samples didn't work with 2.5.3.post2 but it worked if I explicitly installed 2.5.4.

**Comment by philngo** [comment]
@jefffriesen Should be fixed now. There was an issue rendering the readme into RST that prevented it from being properly loaded to PyPI on the last release. Thanks for the heads up.

**Comment by jefffriesen** [comment]
Cool, thanks. That was fast.
