### ISSUE TITLE
caltrack hourly method problem

### ISSUE THREAD

**Issue by LiuJingyao18360** [openeemeter/eemeter#357]
I plan to try EEmeter caltrack hourly method, but there is one line of the code doesn't work. I used the sample data and do exactly the same with the tutorial, but this line of the code just shows error. I wonder if we need a specific version of pandas to run our code? I' m  really confused about it, would you please have a look at this problem?

occupancy_lookup_hourly = eemeter.estimate_hour_of_week_occupancy(
    preliminary_design_matrix_hourly,
    segmentation=segmentation_hourly,
    # threshold=0.65  # default
)

**Comment by LiuJingyao18360** [comment]
The message shows as below:

ValueError                                Traceback (most recent call last)
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'double'

Exception ignored in: 'pandas._libs.lib.is_bool_array'
ValueError: Buffer dtype mismatch, expected 'Python object' but got 'double'

**Comment by philngo** [comment]
Thanks for the report. We recommend pandas using 0.23.4, if that helps. You're seeing this in the scripts/tutorial.ipynb, right? Could you send your eemeter and pandas versions to assist with reproducing the error?

**Comment by philngo** [comment]
Additionally, would you mind pasting in the full traceback, redacted if necessary?

**Comment by LiuJingyao18360** [comment]
Dear Phil,
I've tried pandas 0.21.0 in Anaconda 3 and 0.22.0 in which version Anaconda I forget sorry. They all do not work.
The attachment is the error screenshots.
Thank you for your concern.
Best,
Jingyao
<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=ucbqiue&uid=ucbqiue%40ucl.ac.uk&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22ucbqiue%40ucl.ac.uk%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
ucbqiue
ucbqiue@ucl.ac.uk
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 7/15/2019 23:05，Phil Ngo<notifications@github.com><mailto:notifications@github.com> wrote：

Thanks for the report. We recommend pandas using 0.23.4, if that helps. You're seeing this in the scripts/tutorial.ipynb, right? Could you send your eemeter and pandas versions to assist with reproducing the error?

**Comment by philngo** [comment]
Hi - and the eemeter version?

The attachment does not seem to have gone through. Please paste the traceback text directly?

**Comment by LiuJingyao18360** [comment]
The eemeter version is 2.7.0. I'm not sure what is the traceback text, is the file I attached?

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=ucbqiue&uid=ucbqiue%40ucl.ac.uk&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22ucbqiue%40ucl.ac.uk%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
ucbqiue
ucbqiue@ucl.ac.uk
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 7/16/2019 00:06，Phil Ngo<notifications@github.com><mailto:notifications@github.com> wrote：

Hi - and the eemeter version?

The attachment does not seem to have gone through. Please paste the traceback text directly?

**Comment by philngo** [comment]
Hi, @LiuJingyao18360 -

I've tried, but I haven't yet been able to reproduce the error you are getting with the hourly methods code. I recommend using pandas 0.23.4 and eemeter 2.7.1, or using the docker setup (`docker-compose build`, `docker-compose up jupyter`, then paste the link into a browser). When you send the attachment by email it doesn't seem to be going through (try looking at this issue on github and you'll see how it appears: https://github.com/openeemeter/eemeter/issues/357). The traceback text is the error that python prints out when it fails. I think you've pasted one line of it, but it's generally helpful to see all the lines of the traceback text because it includes references to the lines of code in the library that failed.

**Comment by LiuJingyao18360** [comment]
Hi, Phil. Sorry for the late reply, I've tried pandas 0.23.4 and it works well now.
Thank you for your help!
Best,
Jingyao

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=ucbqiue&uid=ucbqiue%40ucl.ac.uk&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22ucbqiue%40ucl.ac.uk%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
ucbqiue
ucbqiue@ucl.ac.uk
签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 7/23/2019 17:18，Phil Ngo<notifications@github.com><mailto:notifications@github.com> wrote：

Hi, @LiuJingyao18360<https://github.com/LiuJingyao18360> -

I've tried, but I haven't yet been able to reproduce the error you are getting with the hourly methods code. I recommend using pandas 0.23.4 and eemeter 2.7.1, or using the docker setup (docker-compose build, docker-compose up jupyter, then paste the link into a browser). When you send the attachment by email it doesn't seem to be going through (try looking at this issue on github and you'll see how it appears: #357<https://github.com/openeemeter/eemeter/issues/357>). The traceback text is the error that python prints out when it fails. I think you've pasted one line of it, but it's generally helpful to see all the lines of the traceback text because it includes references to the lines of code in the library that failed.

**Comment by LiuJingyao18360** [comment]
The pandas 0.23.4 works well now. Thank you for your help!

**Comment by philngo** [comment]
@LiuJingyao18360 Thanks for reaching out about this issue with the hourly methods. Please consider helping our developer community by filling out our [first-time issue/PR contributor survey](https://forms.gle/zUKkyGUo11CsWE7g8).
