### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by jfenna** [openeemeter/eemeter#456]
Re testing: running both `docker build .` and `docker-compose build` returns an error relating to line 11 in Dockerfile: `executor failed running [/bin/sh -c set -ex && pipenv install --system --deploy --dev]: exit code: 1`. Has this issue been noticed before? Is there a step-by-step testing tutorial that could be shared specific to eemeter?

This occurs for me on Windows 11 running eemeter tests on a unchanged copy of eemeter cloned directly from this repo. Any help much appreciated.

**Comment by ssuffian** [comment]
The docker build and tests were fixed with this PR: https://github.com/openeemeter/eemeter/pull/458. I'm going to close this issue, but if it persists please reopen it!
