### ISSUE TITLE
Releases have not been tracked

### ISSUE THREAD

**Issue by willrrowe** [openeemeter/eemeter#467]
Github page for eemeter shows only v1.0.0 release (https://github.com/openeemeter/eemeter) but looking on pypi we can see there are many more versions that have been released (https://pypi.org/project/eemeter/#history). Ideally these would be consistent.

**Comment by joydeep-recurve** [comment]
Thanks for bringing to our attention! 
Added releases for eemeter. Releases will be consistent going forward. Closing this issue.
