### ISSUE TITLE
Caltrack usage per day predict 

### ISSUE THREAD

**Issue by jillradiantlabs** [openeemeter/eemeter#479]
I am trying to use eemeter.caltrack_usage_per_day_predict with my caltrack daily model to predict usage over a provided prediction index. I get an error:
'DatetimeIndex' object has no attribute 'index'

The error seems to be associated with the computer_temperatures_features step. When I isolate the compute temperature features step with the same values it runs without errors. 

Here is my code with details of each argument for eemeter.caltrack_usage_per_day_predict
```
eemeter.caltrack_usage_per_day_predict(
    baseline_model_results_daily.model.model_type, 
    baseline_model_results_daily.model.model_params,
    normal_year_temperatures_F,
    prediction_index_hourly
    )
```

baseline_model_results_daily.model.model_type= 
> 'cdd_hdd'

baseline_model_results_daily.model.model_params =
> {'intercept': 15.348747394608491,
>  'beta_cdd': 0.9809488470884145,
>  'beta_hdd': 0.37002743650584663,
>  'cooling_balance_point': 55,
>  'heating_balance_point': 55}

normal_year_temperatures_F a series (same error message received if I convert type to dataframe) =

> 2020-10-10 15:00:00+00:00    53.96
> 2020-10-10 16:00:00+00:00    55.94
> 2020-10-10 17:00:00+00:00    57.92
> 2020-10-10 18:00:00+00:00    60.08
> 2020-10-10 19:00:00+00:00    60.98
>                              ...  
> 2021-10-11 10:00:00+00:00    42.98
> 2021-10-11 11:00:00+00:00    44.06
> 2021-10-11 12:00:00+00:00    44.60
> 2021-10-11 13:00:00+00:00    44.96
> 2021-10-11 14:00:00+00:00    44.96
> Freq: H, Length: 8784, dtype: float64

prediction_index_hourly=

> DatetimeIndex(['2020-10-10 15:00:00+00:00', '2020-10-10 16:00:00+00:00',
>                '2020-10-10 17:00:00+00:00', '2020-10-10 18:00:00+00:00',
>                '2020-10-10 19:00:00+00:00', '2020-10-10 20:00:00+00:00',
>                '2020-10-10 21:00:00+00:00', '2020-10-10 22:00:00+00:00',
>                '2020-10-10 23:00:00+00:00', '2020-10-11 00:00:00+00:00',
>                ...
>                '2021-10-11 05:00:00+00:00', '2021-10-11 06:00:00+00:00',
>                '2021-10-11 07:00:00+00:00', '2021-10-11 08:00:00+00:00',
>                '2021-10-11 09:00:00+00:00', '2021-10-11 10:00:00+00:00',
>                '2021-10-11 11:00:00+00:00', '2021-10-11 12:00:00+00:00',
>                '2021-10-11 13:00:00+00:00', '2021-10-11 14:00:00+00:00'],
>               dtype='datetime64[ns, UTC]', length=8784, freq='H')

Here is my code for eemeter.compute_temperature_features

```
eemeter.compute_temperature_features(
    prediction_index_daily, 
    normal_year_temperatures_F, 
    heating_balance_points=None, 
    cooling_balance_points=None, 
    data_quality=False, 
    temperature_mean=True, 
    degree_day_method='daily', 
    percent_hourly_coverage_per_day=0.5, 
    percent_hourly_coverage_per_billing_period=0.9, 
    use_mean_daily_values=True, 
    tolerance=None, 
    keep_partial_nan_rows=True
    )

```
I only post this because this ran successfully when this is what I believe was causing an error in caltrack_usage_per_day_predict.

**Comment by travis-recurve** [comment]
We've released a new daily model. Do you have similar issues?

**Comment by jillradiantlabs** [comment]
All set, thank you!

**Comment by jillradiantlabs** [comment]
Hello, I have a question regarding the transition from EEMeter version 3.2.0 to the latest version, 4.0.0 Specifically, I am seeking guidance on adapting my existing code for weather normalization using EEMeter.

Previously, in version 3.2.0, my process involved:

Creating a daily model using a year's worth of actual temperature and energy use data.Obtaining TMY3 weather data from EEweather.
Utilizing the model to predict energy use with the TMY3 weather, resulting in weather-normalized utility meter data.

An example of the code used for predicting the energy use in a normal year was as follows:
baseline_model_results_daily.model.predict(prediction_index_daily, TMY3_tempF with_disaggregated=True)

However, in version 4.0, I am facing difficulty in understanding how to replicate this process. Although I have successfully created the Daily_Model, I am uncertain about how to proceed with applying this model to a different year of temperature data.

Could you kindly advise on the best approach for transitioning this process into version 4.0 of EEMeter?

Thanks in advance!
Jill

**Comment by travis-recurve** [comment]
Jill take a look at the tutorial in the notebook [here](https://github.com/openeemeter/eemeter/blob/master/scripts/data_and_model_tutorial.ipynb).

Basically, the API has changed. You now only provide the data that it will be fit on when fitting and you call predict on another dataset from which you'd like to get a prediction. If you provide it with TMY3 weather then that's the prediction you'll get.

**Comment by jillradiantlabs** [comment]
Thanks for the reply. I understand that I first create/fit the daily model using the actual temperature data and observed meter data.  For the next dataset that I want to use to predict, this would be comprised of TMY3 temperature data but no meter data. I created a placeholder populated with "nan" for the observed meter data in this dataset. If I use the daily model to predict on this new dataset, would the "predicted" column be the weather normalized results?

**Comment by travis-recurve** [comment]
You'll get results based on the data you input. You'll get the predicted usage for the typical meteorological year as defined by TMY3.
